jazzband/django-invitations

- invitations/adapters.py
This ensures that `get_invitations_adapter` will not return `None` if you have `ACCOUNT_ADAPTER` set but it is *not* set to `'invitations.models.InvitationsAdapter'`.
Fixes #28
> Allow using custom allauth backends.

- invitations/urls.py
With Django 1.9, each time I run `python manage.py runserver`, it shows 2 warnings:
```
/someplace/.venv/lib/python2.7/site-packages/invitations/urls.py:15: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
name='accept-invite'),
/someplace/.venv/lib/python2.7/site-packages/invitations/urls.py:15: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
name='accept-invite'),
```
This pull request fixes it.
> Remove RemovedInDjango110Warning warnings in Django 1.9

- README.md
- invitations/app_settings.py
- invitations/templates/invitations/messages/invite_already_accepted.txt
- invitations/templates/invitations/messages/invite_expired.txt
- invitations/templates/invitations/messages/invite_invalid.txt
- invitations/tests/allauth/test_allauth.py
- invitations/tests/basic/tests.py
- invitations/views.py
Related to #25, similar to #26.
This makes the following changes:
* Adds a new configuration `INVITATIONS_GONE_ON_ACCEPT_ERROR`, defaults to the 'old' behavior of returning an HTTP 410 response on errors.
* If `INVITATIONS_GONE_ON_ACCEPT_ERROR` is `False`, uses messages to tell the user what happened (invalid key, expired key, already accepted key) and redirects.
* Adds a configurable `INVITATIONS_LOGIN_REDIRECT` setting.
* Include tests and documentation.
Please let me know if you'd like to see any changes to this or have any questions.
> Display a message on expired/erroneous/accepted keys. 

- README.md
- invitations/adapters.py
- invitations/app_settings.py
- invitations/tests/basic/tests.py
This would close https://github.com/bee-keeper/django-invitations/issues/40
This PR adds an app setting, `INVITATIONS_EMAIL_SUBJECT_PREFIX`, that allows people to override the subject prefix in email invitations, similar to `ALLAUTH_EMAIL_SUBJECT_PREFIX`. I included a test, but I'm having trouble setting up the test environment properly on my local computer.
> add EMAIL_SUBJECT_PREFIX setting

- invitations/models.py
Although there are blocktrans tags in the templates, without the RequestContext being passed to the rendering process the translation could not swtich to the correct language set in the requests.
> Using RequestContext to provide proper template translation

- README.md
- invitations/adapters.py
- invitations/app_settings.py
- invitations/models.py
- invitations/tests/allauth/test_allauth.py
- invitations/views.py
This PR is to solve the problem addressed in this issue #bee-keeper#25
The change is: a setting variable INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP is added. When it's True, invitations will be accepted after users finish signup. When it's False, invitations will be accepted right after the invitation link is clicked. 
Note that this behavior only works with allauth.
> Add option to accept invite after signup for allauth

- invitations/migrations/0002_auto_20151126_0426.py
- invitations/migrations/0003_auto_20151126_1523.py
- invitations/models.py
Deprecation warnings are being displayed after upgrading to Django 1.10.5. This PR fixes two of the deprecations:
- `on_delete` will be a required arg for ForeignKey in Django 2.0. https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ForeignKey.on_delete
- Importing from django.core.urlresolvers is deprecated in favor of django.urls. I fixed this with a `try` statement so that it doesn't break backwards compatibility with old Django versions.
There are a couple other warnings involving deprecated usage of `django.conf.urls.include()`, but I'm not sure how to fix those since this is a reusable Django app.
To test this, I installed Django 1.10.5 and added `DEBUG = True` to `test_settings.py`. I then ran `python -Wd manage.py runserver` which will display the …
> Fix deprecation warnings

- invitations/forms.py
to fix, just initialize the form:
in the file (rev 1.8)
/invitaitons/forms.py
line 51
` widget=forms.TextInput(attrs={"type": "email", "size": "30"}))`
replace with 
```
widget=forms.TextInput(attrs={"type": "email", "size": "30"}, ),
initial=""
)
```
> invitation form displays "None" when first displayed

- invitations/views.py
I find it quite useful to implement the custom redirect as a function in a subclass of `AcceptInvite`, so that we can redirect to a signup form and pass e.g. the invite ID. I'm not sure if others use this pattern but, if so, this change will allow it (I couldn't find any way of doing it before).
> Added get_signup_redirect to allow custom implementations by subclasses

- README.md
Hi,
Thanks for building this tool. This just adds a required step to the instructions in the README. Without running migrate, users won't be able to use the admin.
Thanks,
Michael
> Adds missing migrations step to installation instructions

- README.md
This is missing in the documentation which causes first time users to get a namespace error. This fixes that issue.
> Add namespace for invitations to urls.py

- invitations/models.py
When you send an invitation to the email, you could need to add extra information in the email. So then I update the `send_invitation` function in order to append the `kwargs` to the context used in the email.
> Added extra context in send invitation

- invitations/adapters.py
- invitations/admin.py
- invitations/app_settings.py
- invitations/forms.py
- invitations/management/commands/clear_expired_invitations.py
- invitations/managers.py
- invitations/migrations/0001_initial.py
- invitations/migrations/0002_auto_20151126_0426.py
- invitations/migrations/0003_auto_20151126_1523.py
- invitations/models.py
- invitations/utils.py
- invitations/views.py
Hello,
how about adding this changes ?
I'd like to use custom forms in some projects, what do you think?
> make forms pluggable

- invitations/views.py
- tests/allauth/test_allauth.py
When using django-allauth and `ACCEPT_INVITE_AFTER_SIGNUP`, the `Invitation` object is obtained by using the new `User`'s email address. Even if a user signs up with an email that differs from the one used on the invite, allauth will normally still associate the `Invitation` email address with the new `User`.
If a user simply alters the case of the email address during signup (user@example.com -> USER@EXAMPLE.COM), allauth's `cleanup_email_addresses()` function can result in the new `User` email matching the case given during signup, rather than the case used on the invite. This will cause the invite to never properly be accepted, as the current implementation of `accept_invite_after_signup()` does not ignore case.
> Ignore email case when accepting invites after signup

- MANIFEST.in
Fixes https://github.com/bee-keeper/django-invitations/issues/119
> MANIFEST.in: Include usual targets

- invitations/views.py
The signal invite_accepted wasn't working due to request not being passed as an argument and the example provided in the signals file wasn't working as well, more details listed below.
https://github.com/bee-keeper/django-invitations/issues/116
I've simply pass request as an argument, all tests seem to be working fine.
Django version used was 1.11
> Passed request as an argument into invite_accepted signal

- invitations/adapters.py
- invitations/models.py
Use `get_current_site` from `django.contrib.sites.shortcuts` instead of hard coding with the `Site` object for better compatibility with multi sites and non-multi sites django instalations. As said in the docs of the function `def get_current_site(request):`
> Check if contrib.sites is installed and return either the current
>     ``Site`` object or a ``RequestSite`` object based on the request
> refactor(models): use get_current_site from django shortcuts

- invitations/admin.py
Showing the admin form takes very long when creating an invitation via the admin on a site with many users. Adding the `inviter` field under `raw_id_fields` makes things faster.
> Make "inviter" be an raw_id_field in admin

- invitations/views.py
The SendInvite view sets the inviter, but the SendJSONInvite view does not.
> Set inviter in SendJSONInvite

- .github/workflows/release.yml
- invitations/urls.py
This was a regression introduced in https://github.com/jazzband/django-invitations/pull/179
> Fix release workflow to actually publish

- .pre-commit-config.yaml
- invitations/adapters.py
- invitations/admin.py
- invitations/forms.py
- invitations/models.py
- invitations/urls.py
- invitations/views.py
- poetry.lock
- pyproject.toml
- test_settings.py
- test_urls.py
- tests/allauth/test_allauth.py
- tests/basic/tests.py
Closes #196
Closes #197
Changes
- use latest published versions of `flake8` and `tox`
References
- https://pypi.org/project/flake8/#history
- https://pypi.org/project/tox/#history
> Fix flake8 and tox dependencies

- invitations/locale/fr/LC_MESSAGES/django.po
Here is a French translation. This is standard French (from France), not the flavour spoken in Quebec (Canada) where they use neologisms like "courriel" instead of the universal "e-mail".
> French translation

- docs/installation.rst
From what I can tell, [Django's sites framework](https://docs.djangoproject.com/en/4.2/ref/contrib/sites/) is no longer required now that #150 has been merged. So, the references to the sites framework in the installation docs can be removed.
It's worth noting that django-allauth still requires the sites framework, but [django-allauth's own docs](https://django-allauth.readthedocs.io/en/latest/installation.html#django) already mention this.
> Remove mention of sites framework from docs

- invitations/views.py
- test_allauth_settings.py
- tests/allauth/test_allauth.py
Fixes #231.
Pass through a `next=...` query parameter to the signup and login views.
The docs for [`SIGNUP_REDIRECT`](https://github.com/jazzband/django-invitations/blob/master/docs/configuration.rst#signup_redirect) and [`LOGIN_REDIRECT`](https://github.com/jazzband/django-invitations/blob/master/docs/configuration.rst#login_redirect) indicate they should be a URL _name_, the default values for these settings are URL names, and the tests for the allauth backend do not override those options and so expect a URL name.
But the [tests for the basic backend](https://github.com/jazzband/django-invitations/blob/a81617da3415fe5f807e575c8d81e6c38b636592/tests/basic/tests.py) override that option with a direct URL:
```python
settings.INVITATIONS_LOGIN_REDIRECT = "/login-url/"
... …
```
> Pass through redirect query arg

- invitations/base_invitation.py
- tests/basic/tests.py
I am not sure if the issue should be closed, since it would be better to prevent `invitations.Invitation` in the DB altogether, when a custom model is used.
> [#203] Add related_name to avoid conflicts when subclassing.
